module.exports = [
  {
    id: "u1",
    pronoun: "",
    firstName: "Stefan",
    lastName: "Åhlander",
    personNumber: 730227,
    email: "cs.ahlander@gmail.com",
    phoneNumber: "0704979766",
    streetAddress_1: "Lapplandsresan 25B",
    streetAddress_2: "",
    postalCode: 75755,
    city: "Uppsala",
    country: "Sweden",
    authenticationProvider: "",
    providerId: "",
    about: "Good guy",
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: "u2",
    pronoun: "",
    firstName: "Maria",
    lastName: "Erlandsson",
    personNumber: 800727,
    email: "cs.ahlander@gmail.com",
    phoneNumber: "0725100580",
    streetAddress_1: "Lapplandsresan 25B",
    streetAddress_2: "",
    postalCode: 75755,
    city: "Uppsala",
    country: "Sweden",
    authenticationProvider: "",
    providerId: "",
    about: "Good girl",
    createdAt: Date.now(),
    updatedAt: Date.now()
  }];