module.exports = [
  {
    pronoun: "",
    name: "Stefan Åhlander",
    personNumber: 730227,
    email: "cs.ahlander@gmail.com",
    phoneNumber: "0704979766",
    streetAddress_1: "Lapplandsresan 25B",
    streetAddress_2: "",
    postalCode: 75755,
    city: "Uppsala",
    country: "Sweden",
    about: "Good guy",
  }, {
    pronoun: "",
    name: "Maria Erlandsson",
    personNumber: 800727,
    email: "maria_erlandsson@hotmail.com",
    phoneNumber: "0725100580",
    streetAddress_1: "Lapplandsresan 25B",
    streetAddress_2: "",
    postalCode: 75755,
    city: "Uppsala",
    country: "Sweden",
    about: "Good girl",
  }, {
    pronoun: "",
    name: "Magnus Asp",
    personNumber: 720727,
    email: "magnus@hotmail.com",
    phoneNumber: "0704881176",
    streetAddress_1: "Stålgatan 41",
    streetAddress_2: "",
    postalCode: 75740,
    city: "Uppsala",
    country: "Sweden",
    about: "",
  }, {
    pronoun: "",
    name: "Gio Garcis",
    personNumber: 750423,
    email: "gio.garcia@gmail.com",
    phoneNumber: "0708118825",
    streetAddress_1: "Lapplandsresan 19A",
    streetAddress_2: "",
    postalCode: 75755,
    city: "Uppsala",
    country: "Sweden",
    about: "Boxer boy",
  }, {
    pronoun: "",
    name: "Jonas Andersson",
    personNumber: 710512,
    email: "berre@hotmail.com",
    phoneNumber: "0705223344",
    streetAddress_1: "Gnejsvägen 19",
    streetAddress_2: "",
    postalCode: 75647,
    city: "Uppsala",
    country: "Sweden",
    about: "Daddy Dj",
  }];
